In [1]:
import pandas as pd
import numpy as np
import scipy.stats

In [4]:
df = pd.read_csv('metrics_50epochs_20augmented.csv')

In [5]:
df

    subject  valence_accuracy  arousal_accuracy  overall_accuracy
0         1           99.8125           99.8125           99.7500
1         2           98.8125           98.9375           98.1250
2         3           99.6875           99.7500           99.5000
3         4           98.7500           98.6250           98.2500
4         5           98.0000           98.1875           97.1875
5         6           99.6875           99.4375           99.3125
6         7          100.0000           99.9375           99.9375
7         8           99.0000           99.6250           98.9375
8         9           96.1250           97.4375           95.5000
9        10           99.0000           98.6875           98.1875
10       11           98.5625           98.2500           97.5625
11       12           99.8750          100.0000           99.8750
12       13           99.3750           99.8125           99.2500
13       14           99.5000           99.3125           99.0625
14       15           99.6250           99.5625           99.4375
15       16           99.6250           99.7500           99.3750
16       17           96.8750           95.8125           93.5625
17       18           99.1250           99.0000           98.5000
18       19           98.3750           98.3750           97.1875
19       20           99.3125           99.5625           99.0000
20       21           99.0000           99.1250           98.6875
21       22           99.1250           99.3750           98.6875
22       23           99.6250           99.9375           99.6250
23       24           97.7500           99.3125           97.3750
24       25           99.7500           99.7500           99.5000
25       26           96.4375           95.6250           95.1250
26       27          100.0000           99.9375           99.9375
27       28           98.6250           98.7500           98.1250
28       29           98.7500           98.9375           98.1875
29       30           99.5625           99.3125           99.1875
30       31           99.4375           99.5000           99.1250
31       32           98.3750           98.4375           97.6250

In [6]:
def mean_confidence_interval(data, confidence=0.95):
    a = 1.0 * np.array(data)
    n = len(a)
    m, se = np.mean(a), scipy.stats.sem(a)
    h = se * scipy.stats.t.ppf((1 + confidence) / 2., n-1)
    return m, m-h, m+h

In [7]:
print(mean_confidence_interval(df['overall_accuracy']))
print(mean_confidence_interval(df['valence_accuracy']))
print(mean_confidence_interval(df['arousal_accuracy']))

(np.float64(98.396484375), np.float64(97.86750881715615), np.float64(98.92545993284385))
(np.float64(98.923828125), np.float64(98.56838050028047), np.float64(99.27927574971953))
(np.float64(98.99609375), np.float64(98.61415910751737), np.float64(99.37802839248263))